# Generated by Django 4.1.13 on 2024-11-12 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCellUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademicYear', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=20)),
                ('Department', models.CharField(default='Enter the department in full form(caps)', max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=20)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=15)),
                ('semester_term', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=15)),
                ('course_instructor', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session', models.CharField(choices=[('FN', 'FN'), ('AN', 'AN')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=15)),
                ('semester', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=5)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH')], max_length=30)),
                ('staffname', models.CharField(max_length=50)),
                ('subjectCode', models.CharField(max_length=10)),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.PositiveIntegerField(blank=True, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('BTlevel_COs', models.CharField(choices=[('R,CO1', 'R,CO1'), ('U,CO1', 'U,CO1'), ('A,CO2', 'A,CO2'), ('Az,CO3', 'Az,CO3'), ('E,CO4', 'E,CO4'), ('C,CO5', 'C,CO5')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('subject', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.newquestion')),
            ],
        ),
    ]
